---
title: "Coxme per art"
author: "Torgeir"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide 
    toc: true
---

## Purpose

In this notebook I will perform Cox Proportional Hazards-models for each species, before I include it in my thesis.

### Why Cox Proportional Hazards?

When doing the GLMM I merely compared the detection rates of each camera between the different periods with and without a flash. I didn't account for whether they in fact had been flashed by the white LED light, only that they had been observed _by the IR camera_ during the periods that the white LED cameras were operable.

So maybe there is a more pronounced effect if I zoom in on the times that the flash actually went off? That can be done with lining up the time stamps from the IR cameras with their white LED camera counterparts to make the `flashed`-variable. `TRUE` when they went of at the same time, `FALSE` if the white LED didn't go off in syncrony.


I should note that sometimes the IR cameras stopped functioning (due to full SD cards etc.), but the white LED cameras continued flashing any animal passing by. Those pictures haven't been sorted, and their existence haven't been included in my data. If the white LED has an effect, some species will have been affected by it untill the next IR period. However, this would only make the intercept of IR _less_ different from the mean intercept of an IR-period.
Whenever a flash has stopped functioning (again - due to empty batteries etc.) the IR period has started immediately, and without my visitation (/presence) affecting the animals.

If anything, these are just examples of what --- other than regular random events --- can cause the variation within the different groups.

# About the model


### Formula

# Modelling


## Roe deer


## Red fox


## Badger


## Moose


## Red deer


## Lynx



## Hare, deer and squirrelywhere (and pine marten)