---
title: "Coxph per art - urbanisation"
author: "Torgeir"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide 
    toc: true
---

```{r setup, include=FALSE, warning=FALSE,message=FALSE, echo=TRUE,}
# 
# knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# options(tibble.print_min = 5)

library(tidyverse)  # entering the tidyverse
library(tidymodels) # and bringing the model-toolbox
library(lubridate)  # lubricating the handling of dates
library(survival)   # the original survival-package
library(survminer)  # a plot-package for ggplot integration
library(vip)        # for variable importance plots
library(pander)     # for prettier outputs of summaries and tables etc.
library(report)     # for reporting test-statistics 
library(equatiomatic) # Model formula displayer in RMarkdown

# Analysis - Survival. Including spatial covariates 
covs<-readRDS("CTloc_covs.rds") %>% select(-geometry) %>% 
  as.data.frame() %>% # Chaning class to data.fram and not a sf data.frame
 mutate(house_d2_ln = ifelse(house_d2 > 0, log(house_d2), 0),
        field_d2_ln = ifelse(field_d2 > 0, log(field_d2), 0),
        elev_ln = log(elev)) 
obs <- readRDS("obs_tte5.rds")%>% # obs prepared for survival analysis (Time_to_Event_Torgeir5.R, line 133)
  rename(species = validated_species) %>% 
  merge(covs, by.x="loc", by.y="LokalitetID", all.x=TRUE, all.y=FALSE) %>% 
  left_join(readRDS("habitat.rds"), by = "loc") 
```

## Purpose

In this notebook I will perform Cox PH analyses again, this time to test for an interaction between the effect of flash and an urbanisation-factor. My hypothesis is this: Animals used to Artifical Light at Night (ALAN) will be less stressed by a white LED light, and therefore their detection rate on CTs will be less affected.


# About the model

In order to find these patterns I can't "remove" the variation between cameras with a random effect. I want this variation to be unaccounted for, so that my spatial covariates can account for the same variation.

The predictor I will have interacting with flash is the distance to nearest house --- log transformed. Transformed because I don't expect the effect of distance to increase linearly, or in other words, change as much from 1000m to 1005m, as from 10m to 15m.

The other variables I'll include are habitat/trail-type, as these features can be thought of as attractants for many species. In addition, a forest road has less vegetation etc. obstructing the view for a camera, and as a result, the detection zone at these sites is larger.
To sum up, the habitat-variable will be used to account for important variance without removing the variation between cameras, that --- possibly --- can be explained by distance to nearest house.

### Why Cox Proportional Hazards?




### Formula


# Modelling

## Roe deer


## Red fox


## Badger


## Moose


## Red deer


## Lynx



## Hare, deer and squirrelywhere (and pine marten)